# fly.toml app configuration file generated for hronica-demo on 2024-01-05T00:46:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hronica-demo"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/ping"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
